k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: do-nyc1-nyc1
  currentCluster: do-nyc1-nyc1
  clusters:
    do-nyc1-nyc1:
      namespace:
        active: kube-system
        favorites:
        - kube-system
        - all
        - monitoring
        - default
      view:
        active: deploy default
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
